# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 12:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_choice', models.CharField(blank=True, choices=[(b'SINGLES', b'Singles Match'), (b'DOUBLES', b'Doubles Match')], default=b'SINGLES', max_length=7, null=True)),
                ('match_date', models.DateField()),
                ('winner_games', models.PositiveIntegerField(default=0)),
                ('loser_games', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_wins', models.IntegerField(default=0)),
                ('game_losses', models.IntegerField(default=0)),
                ('match_wins', models.IntegerField(default=0)),
                ('match_losses', models.IntegerField(default=0)),
                ('point', models.IntegerField(default=0)),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface_choice', models.CharField(choices=[(b'CLAY', b'Clay Court'), (b'HARD', b'Hard Court')], default=b'HARD', max_length=4)),
                ('location_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='loser1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_losing_player', to='tennis.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='loser2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_losing_player2', to='tennis.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tennis.Stadium'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_winning_player', to='tennis.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_winning_player2', to='tennis.Player'),
        ),
    ]
